/**
 * Diagram Viewer Component
 * 
 * Renders diagrams generated by DiagramGenerator.
 * - Inline: compact preview in chat bubble
 * - Tap to open fullscreen modal with close button
 */

import React, { useState } from 'react';
import {
  View,
  StyleSheet,
  ActivityIndicator,
  TouchableOpacity,
  Text,
  Modal,
  Dimensions,
  StatusBar,
  ScrollView,
} from 'react-native';
import { Theme } from '../theme/theme';
import { DiagramGenerator, GeneratedDiagram } from '../../skills/DiagramGenerator';

// Safe WebView import — TurboModule may not be registered during dev with New Architecture
let WebViewComponent: any = null;
try {
  WebViewComponent = require('react-native-webview').WebView;
} catch (e) {
  console.warn('[DiagramViewer] react-native-webview not available, using fallback renderer');
}

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

interface DiagramViewerProps {
  diagram: GeneratedDiagram;
  onError?: (error: string) => void;
  onLoad?: () => void;
}

export const DiagramViewer: React.FC<DiagramViewerProps> = ({
  diagram,
  onError,
  onLoad,
}) => {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [fullscreen, setFullscreen] = useState(false);

  const handleLoad = () => {
    setLoading(false);
    onLoad?.();
  };

  const handleError = (syntheticEvent: any) => {
    const { nativeEvent } = syntheticEvent;
    const errorMessage = `Failed to load diagram: ${nativeEvent.description}`;
    setError(errorMessage);
    setLoading(false);
    onError?.(errorMessage);
  };

  const handleMessage = (event: any) => {
    try {
      const data = JSON.parse(event.nativeEvent.data);
      if (data.type === 'READY') {
        setLoading(false);
      }
    } catch (e) {
      // Not a JSON message or different format
    }
  };

  const getLibraryLabel = (): { label: string; color: string } => {
    const badges: Record<string, { label: string; color: string }> = {
      katex: { label: 'KaTeX', color: '#008080' },
      jsxgraph: { label: 'JSXGraph', color: '#2DD4BF' },
      smilesdrawer: { label: 'SmilesDrawer', color: '#818CF8' },
      svg: { label: 'SVG', color: '#10b981' },
    };
    return badges[diagram.library] || { label: diagram.library, color: Theme.colors.primary };
  };

  /**
   * Fallback renderer when WebView is unavailable.
   */
  const renderFallback = () => (
    <View style={styles.fallbackContainer}>
      <Text style={styles.fallbackIcon}>📊</Text>
      <Text style={styles.fallbackTitle}>Diagram Generated</Text>
      <Text style={styles.fallbackSubtitle}>
        Tap to view • WebView required for interactive rendering
      </Text>
      <ScrollView style={styles.fallbackCodeScroll} nestedScrollEnabled>
        <Text style={styles.fallbackCode} selectable>
          {diagram.code.substring(0, 300)}...
        </Text>
      </ScrollView>
    </View>
  );

  const INJECTED_JS = `
    (function() {
      function fixDiagram() {
        var svgs = document.querySelectorAll('svg');
        svgs.forEach(function(svg) {
          try {
            var bbox = svg.getBBox();
            if (bbox.width > 0 && bbox.height > 0) {
              var padding = 50;
              var newViewBox = [
                bbox.x - padding,
                bbox.y - padding,
                bbox.width + (padding * 2),
                bbox.height + (padding * 2)
              ].join(' ');
              svg.setAttribute('viewBox', newViewBox);
              svg.style.width = '100%';
              svg.style.height = '100%';
              svg.style.maxWidth = 'none';
              svg.style.maxHeight = 'none';
              svg.setAttribute('preserveAspectRatio', 'xMidYMid meet');
              
              // Force body centering
              document.body.style.margin = '0';
              document.body.style.padding = '0';
              document.body.style.overflow = 'hidden';
              document.body.style.display = 'flex';
              document.body.style.justifyContent = 'center';
              document.body.style.alignItems = 'center';
              document.body.style.width = '100vw';
              document.body.style.height = '100vh';
              document.documentElement.style.width = '100vw';
              document.documentElement.style.height = '100vh';

              var container = document.querySelector('.svg-container');
              if (container) {
                container.style.padding = '0';
                container.style.margin = '0';
                container.style.width = '100%';
                container.style.height = '100%';
              }
            }
          } catch (e) {}
        });
      }
      
      fixDiagram();
      setTimeout(fixDiagram, 300);
      setTimeout(fixDiagram, 1000);
    })();
    true;
  `;

  const renderWebView = (isFullscreen: boolean) => {
    if (!WebViewComponent) return renderFallback();

    const html = diagram.renderHtml || DiagramGenerator.getHtmlForLibrary(diagram.library, diagram.code);

    return (
      <WebViewComponent
        source={{ html }}
        style={isFullscreen ? styles.fullscreenWebview : styles.inlineWebview}
        onLoad={handleLoad}
        onError={handleError}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        injectedJavaScript={INJECTED_JS}
        startInLoadingState={false}
        scalesPageToFit={false}
        scrollEnabled={isFullscreen}
        showsVerticalScrollIndicator={false}
        showsHorizontalScrollIndicator={false}
        originWhitelist={['*']}
        mixedContentMode="always"
        allowFileAccess={true}
        allowUniversalAccessFromFileURLs={true}
        nestedScrollEnabled={true}
        containerStyle={{ backgroundColor: 'transparent' }}
        onMessage={handleMessage}
      />
    );
  };

  const badge = getLibraryLabel();

  return (
    <>
      {/* Inline Preview (in chat) */}
      <TouchableOpacity
        activeOpacity={0.85}
        onPress={() => setFullscreen(true)}
        style={styles.inlineContainer}
      >
        {/* Tiny badge + tap hint */}
        <View style={styles.inlineHeader}>
          <View style={[styles.badge, { borderColor: badge.color }]}>
            <Text style={[styles.badgeText, { color: badge.color }]}>{badge.label}</Text>
          </View>
          <Text style={styles.tapHint}>Tap to expand ↗</Text>
        </View>

        {/* Inline diagram preview */}
        <View style={styles.inlinePreview}>
          {loading && WebViewComponent && (
            <View style={styles.loadingOverlay}>
              <ActivityIndicator size="small" color={Theme.colors.primary} />
            </View>
          )}
          {error ? (
            <View style={styles.errorContainer}>
              <Text style={styles.errorText}>❌ {error}</Text>
            </View>
          ) : (
            renderWebView(false)
          )}
        </View>
      </TouchableOpacity>

      {/* Fullscreen Modal */}
      <Modal
        visible={fullscreen}
        animationType="fade"
        transparent={false}
        statusBarTranslucent
        onRequestClose={() => setFullscreen(false)}
      >
        <View style={styles.fullscreenContainer}>
          <StatusBar backgroundColor="#f8fafc" barStyle="dark-content" />

          {/* Close Button */}
          <TouchableOpacity
            style={styles.closeButton}
            onPress={() => setFullscreen(false)}
            hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}
          >
            <Text style={styles.closeButtonText}>✕</Text>
          </TouchableOpacity>

          {/* Topic label */}
          <View style={styles.fullscreenHeader}>
            <View style={[styles.badge, { borderColor: badge.color }]}>
              <Text style={[styles.badgeText, { color: badge.color }]}>{badge.label}</Text>
            </View>
            <Text style={styles.fullscreenTopic} numberOfLines={1}>
              {diagram.metadata.topic}
            </Text>
          </View>

          {/* Full diagram */}
          <View style={styles.fullscreenBody}>
            {renderWebView(true)}
          </View>
        </View>
      </Modal>
    </>
  );
};

const styles = StyleSheet.create({
  // ==================== Inline Preview ====================
  inlineContainer: {
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingHorizontal: 4, // Minor buffer
  },
  inlineHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  tapHint: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: '500',
  },
  inlinePreview: {
    height: 340,
    position: 'relative',
    padding: 10, // Buffer for SVG labels
  },
  inlineWebview: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    zIndex: 10,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    fontSize: 13,
    color: '#ef4444',
    textAlign: 'center',
  },

  // ==================== Fullscreen Modal ====================
  fullscreenContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  closeButton: {
    position: 'absolute',
    top: 48,
    right: 20,
    zIndex: 100,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  closeButtonText: {
    fontSize: 18,
    color: '#000000',
    fontWeight: '300',
  },
  fullscreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 52,
    paddingHorizontal: 20,
    paddingBottom: 12,
    gap: 10,
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  fullscreenTopic: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000000',
    flex: 1,
  },
  fullscreenBody: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  fullscreenWebview: {
    flex: 1,
    backgroundColor: '#ffffff',
  },

  // ==================== Fallback ====================
  fallbackContainer: {
    padding: 16,
    alignItems: 'center',
  },
  fallbackIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  fallbackTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#dae2fd',
    marginBottom: 4,
  },
  fallbackSubtitle: {
    fontSize: 12,
    color: 'rgba(218, 226, 253, 0.5)',
    marginBottom: 12,
  },
  fallbackCodeScroll: {
    width: '100%',
    maxHeight: 150,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    padding: 10,
  },
  fallbackCode: {
    fontSize: 11,
    fontFamily: 'monospace',
    color: '#a5b4fc',
    lineHeight: 16,
  },
});
