import React, { useState, useRef, useCallback, useEffect } from 'react';
import {
  View, Text, StyleSheet, TextInput,
  TouchableOpacity, FlatList,
  KeyboardAvoidingView, Platform, ActivityIndicator, Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Theme } from '../theme/theme';
import { StudentProfileStore } from '../../core/storage/StudentProfile';
import { OnboardingProgressStore } from '../../core/storage/OnboardingProgress';
import { SemanticMemoryInstance } from '../../core/memory/SemanticMemory';
import { ThinkingIndicator } from '../components/ThinkingIndicator';
import { AIBubble } from '../components/AIBubble';
import { StudentProfiler } from '../../core/profiling/StudentProfiler';
import { ModelManager, ChatMessage, ChatRole } from '../../core/api/ModelManager';
import { Sparkles, ArrowRight, CheckCircle2, Brain } from 'lucide-react-native';

// Memoir (semantic memory) singleton — used for fact storage and retrieval during onboarding
const semanticMemory = SemanticMemoryInstance;

interface Message {
  id: string;
  role: 'ai' | 'user';
  content: string;
}

// System prompt is now dynamically generated by StudentProfiler

interface Props {
  onComplete: () => void;
  onSkip?: () => void;
}

export const OnboardingChat: React.FC<Props> = ({ onComplete, onSkip }) => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [isFirstMsgLoading, setIsFirstMsgLoading] = useState(true);
  const [input, setInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isFinished, setIsFinished] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [phaseProgress, setPhaseProgress] = useState(0);

  const profiler = useRef(new StudentProfiler()).current;
  const flatListRef = useRef<FlatList>(null);
  // semantic memory is now used via singleton in handleSend and saveProgress
  // Throttle refs for streaming
  const lastStreamUpdate = useRef<number>(0);
  const pendingContent = useRef<string>('');
  
  // MEMOIR CRASH PREVENTION: Limit message history to prevent OOM
  const MAX_ONBOARDING_MESSAGES = 20; // ~10 turns max

  const saveProgress = useCallback(async () => {
    try {
      await OnboardingProgressStore.saveProgress({
        messages: messages.map(m => ({
          role: m.role,
          content: m.content,
          timestamp: Date.now(),
        })),
        semanticFacts: semanticMemory.getAllFacts(),
        questionCount: phaseProgress,
        lastUpdated: Date.now(),
        isComplete: isFinished,
      });
    } catch (e) {
      console.error('[OnboardingChat] Failed to save progress:', e);
    }
  }, [messages, semanticMemory, phaseProgress, isFinished]);

  const loadSavedProgress = useCallback(async () => {
    try {
      const saved = await OnboardingProgressStore.loadProgress();
      if (saved && !saved.isComplete && saved.messages.length > 1) {
        // Ask user if they want to resume
        Alert.alert(
          'Resume Onboarding?',
          `You have ${saved.questionCount} saved responses. Continue where you left off?`,
          [
            {
              text: 'Start Fresh',
              onPress: async () => {
                await OnboardingProgressStore.clearProgress();
                setIsLoading(false);
              },
              style: 'cancel',
            },
            {
              text: 'Resume',
              onPress: () => {
                setMessages(saved.messages.map((m, i) => ({
                  id: i.toString(),
                  role: m.role,
                  content: m.content,
                })));
                setPhaseProgress(saved.questionCount);
                
                // SemanticMemoryInstance already loaded facts at module init
                if (saved.semanticFacts) {
                  console.log('[SemanticMemory] Loaded', saved.semanticFacts.length, 'facts');
                }
                
                setIsLoading(false);
                setTimeout(() => flatListRef.current?.scrollToEnd({ animated: true }), 300);
              },
            },
          ]
        );
      } else {
        setIsLoading(false);
      }
    } catch (e) {
      console.error('[OnboardingChat] Failed to load progress:', e);
      setIsLoading(false);
    }
  }, [semanticMemory, flatListRef]);

  useEffect(() => {
    // Initial greeting
    if (messages.length === 0 && !isLoading) {
      setMessages([
        { 
          id: '0', 
          role: 'ai', 
          content: "Welcome to Padh.ai. I am the Elite Cognitive Architect. We are here to initialize your high-performance learning path. To begin the cognitive scan, I need your full identity. What is your name?" 
        }
      ]);
      setTimeout(() => setIsFirstMsgLoading(false), 2000);
    }
  }, [isLoading, messages.length]);

  // Load saved progress on mount (SemanticMemoryInstance auto-loads at module init)
  useEffect(() => {
    loadSavedProgress();
  }, [loadSavedProgress]);

  // Auto-save progress after each message
  useEffect(() => {
    if (!isLoading && messages.length > 1) {
      saveProgress();
    }
  }, [messages, phaseProgress, isLoading, saveProgress]);

  const handleSend = useCallback(async () => {
    if (!input.trim() || isGenerating || isFinished) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: input.trim(),
    };

    const aiPlaceholder: Message = {
      id: (Date.now() + 1).toString(),
      role: 'ai',
      content: '',
    };

    setMessages(prev => {
      // MEMOIR CRASH PREVENTION: Trim old messages to prevent OOM
      const updated = [...prev, userMessage, aiPlaceholder];
      if (updated.length > MAX_ONBOARDING_MESSAGES) {
        // Keep first message (greeting) and recent messages
        return [updated[0], ...updated.slice(-(MAX_ONBOARDING_MESSAGES - 1))];
      }
      return updated;
    });
    setInput('');
    setIsGenerating(true);
    // isThinking logic removed as it was unused state

    try {
      // 1. Process response in profiler BEFORE generating AI response
      const nextPhase = profiler.processResponse(input.trim(), "");
      setPhaseProgress(profiler.getProgress());
      
      // MEMOIR INTEGRATION: Store facts in hierarchical memory
      const extractedFacts = profiler.getState().facts;
      await semanticMemory.addFacts(extractedFacts);
      console.log(`[OnboardingChat] Stored ${extractedFacts.length} facts in hierarchical memory`);

      const currentSystemPrompt = profiler.getSystemPrompt();
      
      // MEMOIR CRASH PREVENTION: Use only recent history + semantic context
      // Instead of full chat history, use last 3 turns + memory state vector
      const recentMessages: ChatMessage[] = messages
        .slice(-6) // Last 3 turns (6 messages)
        .map(m => ({
          role: (m.role === 'ai' ? 'assistant' : 'user') as ChatRole,
          content: m.content
        }))
        .filter(m => m.content && m.content.length > 0);

      // Get compact memory context (replaces full history)
      const memoryContext = await semanticMemory.getRelevantContextAsync('onboarding', 60);
      
      // Build compact system prompt with memory state
      const compactSystemPrompt = currentSystemPrompt + 
        (memoryContext ? `\n\nMEMORY STATE:\n${memoryContext}` : '');

      let fullContent = "";
      let hasStartedGenerating = false;

      await ModelManager.streamChat(
        [
          { role: 'system', content: compactSystemPrompt },
          ...recentMessages,
          { role: 'user', content: input.trim() }
        ],
        (token) => {
          if (!hasStartedGenerating) {
            hasStartedGenerating = true;
          }
          
          fullContent += token;
          pendingContent.current = fullContent;

          const now = Date.now();
          if (now - lastStreamUpdate.current >= 60) {
            const snapshot = pendingContent.current;
            setMessages(prev => {
              const updated = [...prev];
              const last = updated[updated.length - 1];
              last.content = snapshot;
              return [...updated];
            });
            lastStreamUpdate.current = now;
          }
        }
      );

      // 2. Check if we are finished
      if (nextPhase === 'complete') {
        setIsFinished(true);
        await OnboardingProgressStore.clearProgress();
        
        const finalData = profiler.getState().data;
        await StudentProfileStore.save({
          ...finalData,
          onboardingComplete: true,
          id: 'student_' + Date.now(),
        } as any);
      }

    } catch (e) {
      console.error("[OnboardingChat] Error during message handling:", e);
      
      // Check if it's a memory/crash related error
      const errorMsg = e instanceof Error ? e.message : String(e);
      const isMemoryError = errorMsg.toLowerCase().includes('memory') || 
                           errorMsg.toLowerCase().includes('out of') ||
                           errorMsg.toLowerCase().includes('crash');
      
      setMessages(prev => {
        const updated = [...prev];
        if (isMemoryError) {
          updated[updated.length - 1].content = 
            "I'm experiencing memory issues. Your progress is saved. Please restart the app to continue.";
        } else {
          updated[updated.length - 1].content = `I'm having trouble: ${errorMsg}. Let's try again?`;
        }
        return updated;
      });
      
      // Save progress even on error
      await saveProgress();
    } finally {
      setIsGenerating(false);
      setTimeout(() => flatListRef.current?.scrollToEnd({ animated: true }), 100);
    }
  }, [input, isGenerating, isFinished, messages, profiler, saveProgress]);

  const renderMessage = ({ item }: { item: Message }) => {
    const isLastMessage = messages[messages.length - 1]?.id === item.id;
    const isGeneratingMessage = (isLastMessage && item.role === 'ai' && isGenerating) || (item.id === '0' && isFirstMsgLoading);

    return (
      <View style={[
        styles.messageBubble,
        item.role === 'user' ? styles.userBubble : styles.aiBubble,
      ]}>
        {item.role === 'ai' && (
          <View style={styles.thinkingAvatarContainer}>
            <View style={styles.aiIconCircle}>
              <Brain size={18} color={Theme.colors.primary} />
            </View>
          </View>
        )}
        <View style={[
          styles.bubbleContent,
          item.role === 'user' ? styles.userContent : styles.aiContent,
        ]}>
          {item.role === 'ai' ? (
            <AIBubble 
              content={item.content} 
              isStreaming={isGeneratingMessage}
            />
          ) : (
            <Text style={styles.messageText}>{item.content}</Text>
          )}
        </View>
      </View>
    );
  };



  if (isLoading) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <ThinkingIndicator text="Loading..." />
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerTopRow}>
          <View style={styles.titleGroup}>
            <View style={styles.iconCircle}>
              <Sparkles size={20} color={Theme.colors.primary} />
            </View>
            <View>
              <Text style={styles.headerTitle}>Personalize Padh.ai</Text>
              <Text style={styles.headerSubtitle}>Phase {phaseProgress + 1} of {profiler.getTotalPhases()}</Text>
            </View>
          </View>
          {onSkip && (
            <TouchableOpacity onPress={onSkip} style={styles.skipBtn}>
              <Text style={styles.skipBtnText}>Skip</Text>
            </TouchableOpacity>
          )}
        </View>
        <View style={styles.progressRow}>
          {[...Array(profiler.getTotalPhases())].map((_, i) => (
            <View
              key={i}
              style={[
                styles.progressDot,
                i < phaseProgress ? styles.progressDotActive : null,
              ]}
            />
          ))}
        </View>
      </View>

      {/* Chat and Input wrapped in KeyboardAvoidingView */}
      {/* iOS: padding behavior with offset for header+status bar (~150px) */}
      {/* Android: adjustResize in manifest handles it natively */}
      <KeyboardAvoidingView
        style={styles.keyboardView}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        keyboardVerticalOffset={Platform.OS === 'ios' ? 120 : 0}
      >
        <FlatList
          ref={flatListRef}
          data={messages}
          keyExtractor={item => item.id}
          renderItem={renderMessage}
          contentContainerStyle={styles.chatContent}
          showsVerticalScrollIndicator={false}
          keyboardShouldPersistTaps="handled"
          onContentSizeChange={() => flatListRef.current?.scrollToEnd({ animated: true })}
          onLayout={() => flatListRef.current?.scrollToEnd({ animated: true })}
        />

        {!isFinished ? (
          <View style={styles.inputArea}>
            <View style={styles.inputContainer}>
              <TextInput
                style={styles.input}
                placeholder="Your answer..."
                placeholderTextColor={Theme.colors.textMuted}
                value={input}
                onChangeText={setInput}
                onSubmitEditing={handleSend}
                returnKeyType="send"
                multiline={false}
                editable={!isGenerating}
                blurOnSubmit={false}
              />
              <TouchableOpacity
                style={[styles.sendBtn, (!input.trim() || isGenerating) && styles.sendBtnDisabled]}
                onPress={handleSend}
                disabled={!input.trim() || isGenerating}
                activeOpacity={0.7}
              >
                {isGenerating ? (
                  <ActivityIndicator color="#FFF" size="small" />
                ) : (
                  <ArrowRight size={22} color="#FFF" />
                )}
              </TouchableOpacity>
            </View>
          </View>
        ) : (
          <TouchableOpacity style={styles.startBtn} onPress={onComplete} activeOpacity={0.8}>
            <View style={styles.startBtnContent}>
              <Text style={styles.startBtnText}>Initialize Learning Engine</Text>
              <CheckCircle2 size={20} color="#FFF" />
            </View>
          </TouchableOpacity>
        )}
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 10 : 24,
    paddingBottom: 20,
    backgroundColor: 'rgba(11, 19, 38, 0.9)',
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.glassBorder,
    zIndex: 10,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  titleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconCircle: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(99, 102, 241, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.3)',
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: Theme.fonts.bold,
    color: Theme.colors.text,
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 12,
    color: Theme.colors.textSecondary,
    fontFamily: Theme.fonts.medium,
    marginTop: 2,
  },
  skipBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: Theme.colors.surfaceHigh,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Theme.colors.glassBorder,
  },
  skipBtnText: {
    fontSize: 12,
    fontFamily: Theme.fonts.bold,
    color: Theme.colors.textMuted,
    textTransform: 'uppercase',
  },
  progressRow: {
    flexDirection: 'row',
    gap: 8,
  },
  progressDot: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  progressDotActive: {
    backgroundColor: Theme.colors.secondary,
    shadowColor: Theme.colors.secondary,
    shadowRadius: 6,
    shadowOpacity: 0.6,
  },
  chatContent: {
    padding: 20,
    paddingBottom: 40,
  },
  messageBubble: {
    flexDirection: 'row',
    marginBottom: 24,
    maxWidth: '88%',
  },
  userBubble: {
    alignSelf: 'flex-end',
    flexDirection: 'row-reverse',
  },
  aiBubble: {
    alignSelf: 'flex-start',
  },
  thinkingAvatarContainer: {
    width: 40,
    height: 40,
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginRight: 8,
    marginTop: 4,
  },
  aiIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.2)',
  },
  bubbleContent: {
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  userContent: {
    backgroundColor: Theme.colors.primary,
    borderBottomRightRadius: 4,
    ...Theme.shadow.md,
  },
  aiContent: {
    backgroundColor: Theme.colors.surfaceCard,
    borderWidth: 1,
    borderColor: Theme.colors.glassBorder,
    borderBottomLeftRadius: 4,
  },
  messageText: {
    fontSize: 16,
    color: Theme.colors.text,
    lineHeight: 24,
    fontFamily: Theme.fonts.medium,
  },
  inputArea: {
    padding: 16,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.glassBorder,
    backgroundColor: Theme.colors.background,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.surfaceHigh,
    borderRadius: 30,
    paddingLeft: 20,
    paddingRight: 6,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: Theme.colors.glassBorder,
  },
  input: {
    flex: 1,
    height: 48,
    color: Theme.colors.text,
    fontSize: 16,
    fontFamily: Theme.fonts.medium,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Theme.colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    ...Theme.shadow.glow,
  },
  sendBtnDisabled: {
    opacity: 0.3,
    backgroundColor: Theme.colors.surfaceMuted,
  },
  startBtn: {
    margin: 20,
    marginBottom: Platform.OS === 'ios' ? 50 : 30,
    height: 68,
    borderRadius: 20,
    backgroundColor: Theme.colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    ...Theme.shadow.glow,
  },
  startBtnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  startBtnText: {
    color: '#FFF',
    fontSize: 18,
    fontFamily: Theme.fonts.bold,
    letterSpacing: 0.5,
  },
  keyboardView: {
    flex: 1,
  },
});
